// Generato da scripts/import-azure-icons.mjs a partire dal set ufficiale Microsoft Azure
// Architecture Icons (tmp/azure-icons-src/, non versionata). Non modificare a mano: rilanciare lo
// script se Microsoft aggiorna il set. 636 icone.
import type { IconOption } from "./iconifyIcons";

export const AZURE_ICON_CATALOG: IconOption[] = [
  { id: "azure/abs-member", label: "ABS Member" },
  { id: "azure/active-directory-connect-health", label: "Active Directory Connect Health" },
  { id: "azure/activity-log", label: "Activity Log" },
  { id: "azure/administrative-units", label: "Administrative Units" },
  { id: "azure/advisor", label: "Advisor" },
  { id: "azure/agentic-web-apps", label: "Agentic Web Apps" },
  { id: "azure/ai-at-edge", label: "AI at Edge" },
  { id: "azure/ai-foundry", label: "AI Foundry" },
  { id: "azure/ai-gateway", label: "AI Gateway" },
  { id: "azure/ai-studio", label: "AI Studio" },
  { id: "azure/aks-automatic", label: "AKS Automatic" },
  { id: "azure/aks-istio", label: "AKS Istio" },
  { id: "azure/aks-network-policy", label: "AKS Network Policy" },
  { id: "azure/alerts", label: "Alerts" },
  { id: "azure/all-resources", label: "All Resources" },
  { id: "azure/analysis-services", label: "Analysis Services" },
  { id: "azure/anomaly-detector", label: "Anomaly Detector" },
  { id: "azure/api-center", label: "API Center" },
  { id: "azure/api-connections", label: "API Connections" },
  { id: "azure/api-management-services", label: "API Management Services" },
  { id: "azure/api-proxy", label: "API Proxy" },
  { id: "azure/app-compliance-automation", label: "App Compliance Automation" },
  { id: "azure/app-configuration", label: "App Configuration" },
  { id: "azure/app-registrations", label: "App Registrations" },
  { id: "azure/app-service-certificates", label: "App Service Certificates" },
  { id: "azure/app-service-domains", label: "App Service Domains" },
  { id: "azure/app-service-environments", label: "App Service Environments" },
  { id: "azure/app-service-plans", label: "App Service Plans" },
  { id: "azure/app-services", label: "App Services" },
  { id: "azure/app-space", label: "App Space" },
  { id: "azure/app-space-component", label: "App Space Component" },
  { id: "azure/applens", label: "Applens" },
  { id: "azure/application-gateway-containers", label: "Application Gateway Containers" },
  { id: "azure/application-gateways", label: "Application Gateways" },
  { id: "azure/application-group", label: "Application Group" },
  { id: "azure/application-insights", label: "Application Insights" },
  { id: "azure/application-security-groups", label: "Application Security Groups" },
  { id: "azure/aquila", label: "Aquila" },
  { id: "azure/arc-data-services", label: "Arc Data services" },
  { id: "azure/arc-kubernetes", label: "Arc Kubernetes" },
  { id: "azure/arc-machines", label: "Arc Machines" },
  { id: "azure/arc-postgresql", label: "Arc PostgreSQL" },
  { id: "azure/arc-sql-managed-instance", label: "Arc SQL Managed Instance" },
  { id: "azure/arc-sql-server", label: "Arc SQL Server" },
  { id: "azure/atm-multistack", label: "ATM Multistack" },
  { id: "azure/auto-scale", label: "Auto Scale" },
  { id: "azure/automanaged-vm", label: "Automanaged VM" },
  { id: "azure/automation-accounts", label: "Automation Accounts" },
  { id: "azure/availability-sets", label: "Availability Sets" },
  { id: "azure/avs-vm", label: "AVS VM" },
  { id: "azure/azure-a", label: "Azure A" },
  { id: "azure/azure-access-point", label: "Azure Access Point" },
  { id: "azure/azure-ad-b2c", label: "Azure AD B2C" },
  { id: "azure/azure-ai-foundry-iq", label: "Azure AI Foundry IQ" },
  { id: "azure/azure-api-for-fhir", label: "Azure API for FHIR" },
  { id: "azure/azure-app-testing", label: "Azure App Testing" },
  { id: "azure/azure-applied-ai-services", label: "Azure Applied AI Services" },
  { id: "azure/azure-arc", label: "Azure Arc" },
  { id: "azure/azure-backup-center", label: "Azure Backup Center" },
  { id: "azure/azure-blockchain-service", label: "Azure Blockchain Service" },
  { id: "azure/azure-center-for-sap", label: "Azure Center for SAP" },
  { id: "azure/azure-chaos-studio", label: "Azure Chaos Studio" },
  { id: "azure/azure-cloud-shell", label: "Azure Cloud Shell" },
  { id: "azure/azure-communication-services", label: "Azure Communication Services" },
  { id: "azure/azure-communications-gateway", label: "Azure Communications Gateway" },
  { id: "azure/azure-compute-galleries", label: "Azure Compute Galleries" },
  { id: "azure/azure-consumption-commitment", label: "Azure Consumption Commitment" },
  { id: "azure/azure-container-storage", label: "Azure Container Storage" },
  { id: "azure/azure-cosmos-db", label: "Azure Cosmos DB" },
  { id: "azure/azure-data-catalog", label: "Azure Data Catalog" },
  { id: "azure/azure-data-explorer-clusters", label: "Azure Data Explorer Clusters" },
  { id: "azure/azure-data-sharing", label: "Azure Data Sharing" },
  { id: "azure/azure-data-transfer", label: "Azure Data Transfer" },
  { id: "azure/azure-database-mariadb-server", label: "Azure Database MariaDB Server" },
  { id: "azure/azure-database-migration-services", label: "Azure Database Migration Services" },
  { id: "azure/azure-database-mysql-server", label: "Azure Database MySQL Server" },
  { id: "azure/azure-database-postgresql-server", label: "Azure Database PostgreSQL Server" },
  { id: "azure/azure-database-postgresql-server-group", label: "Azure Database PostgreSQL Server Group" },
  { id: "azure/azure-databox-gateway", label: "Azure Databox Gateway" },
  { id: "azure/azure-databricks", label: "Azure Databricks" },
  { id: "azure/azure-deployment-environments", label: "Azure Deployment Environments" },
  { id: "azure/azure-dev-tunnels", label: "Azure Dev Tunnels" },
  { id: "azure/azure-devops", label: "Azure DevOps" },
  { id: "azure/azure-documentdb", label: "Azure DocumentDB" },
  { id: "azure/azure-edge-hardware-center", label: "Azure Edge Hardware Center" },
  { id: "azure/azure-enclaves", label: "Azure Enclaves" },
  { id: "azure/azure-experimentation-studio", label: "Azure Experimentation Studio" },
  { id: "azure/azure-fileshares", label: "Azure Fileshares" },
  { id: "azure/azure-firewall-manager", label: "Azure Firewall Manager" },
  { id: "azure/azure-firewall-policy", label: "Azure Firewall Policy" },
  { id: "azure/azure-hcp-cache", label: "Azure HCP Cache" },
  { id: "azure/azure-hpc-workbenches", label: "Azure HPC Workbenches" },
  { id: "azure/azure-hybrid-center", label: "Azure Hybrid Center" },
  { id: "azure/azure-information-protection", label: "Azure Information Protection" },
  { id: "azure/azure-iot-operations", label: "Azure IoT Operations" },
  { id: "azure/azure-lighthouse", label: "Azure Lighthouse" },
  { id: "azure/azure-linux", label: "Azure Linux" },
  { id: "azure/azure-load-testing", label: "Azure Load Testing" },
  { id: "azure/azure-local", label: "Azure Local" },
  { id: "azure/azure-machine-learning", label: "Azure Machine Learning" },
  { id: "azure/azure-managed-grafana", label: "Azure Managed Grafana" },
  { id: "azure/azure-managed-redis", label: "Azure Managed Redis" },
  { id: "azure/azure-maps-accounts", label: "Azure Maps Accounts" },
  { id: "azure/azure-media-service", label: "Azure Media Service" },
  { id: "azure/azure-migrate", label: "Azure Migrate" },
  { id: "azure/azure-monitor-dashboard", label: "Azure Monitor Dashboard" },
  { id: "azure/azure-monitor-pipeline", label: "Azure Monitor Pipeline" },
  { id: "azure/azure-monitors-for-sap-solutions", label: "Azure Monitors for SAP Solutions" },
  { id: "azure/azure-netapp-files", label: "Azure NetApp Files" },
  { id: "azure/azure-network-function-manager", label: "Azure Network Function Manager" },
  { id: "azure/azure-network-function-manager-functions", label: "Azure Network Function Manager Functions" },
  { id: "azure/azure-object-understanding", label: "Azure Object Understanding" },
  { id: "azure/azure-openai", label: "Azure OpenAI" },
  { id: "azure/azure-operator-5g-core", label: "Azure Operator 5G Core" },
  { id: "azure/azure-operator-insights", label: "Azure Operator Insights" },
  { id: "azure/azure-operator-nexus", label: "Azure Operator Nexus" },
  { id: "azure/azure-operator-service-manager", label: "Azure Operator Service Manager" },
  { id: "azure/azure-orbital", label: "Azure Orbital" },
  { id: "azure/azure-programmable-connectivity", label: "Azure Programmable Connectivity" },
  { id: "azure/azure-quotas", label: "Azure Quotas" },
  { id: "azure/azure-red-hat-openshift", label: "Azure Red Hat OpenShift" },
  { id: "azure/azure-sentinel", label: "Azure Sentinel" },
  { id: "azure/azure-service-bus", label: "Azure Service Bus" },
  { id: "azure/azure-sphere", label: "Azure Sphere" },
  { id: "azure/azure-spring-apps", label: "Azure Spring Apps" },
  { id: "azure/azure-sql", label: "Azure SQL" },
  { id: "azure/azure-sql-edge", label: "Azure SQL Edge" },
  { id: "azure/azure-sql-server-stretch-databases", label: "Azure SQL Server Stretch Databases" },
  { id: "azure/azure-sql-vm", label: "Azure SQL VM" },
  { id: "azure/azure-stack-hci-sizer", label: "Azure Stack HCI Sizer" },
  { id: "azure/azure-storage-mover", label: "Azure Storage Mover" },
  { id: "azure/azure-support-center-blue", label: "Azure Support Center Blue" },
  { id: "azure/azure-sustainability", label: "Azure Sustainability" },
  { id: "azure/azure-synapse-analytics", label: "Azure Synapse Analytics" },
  { id: "azure/azure-token-service", label: "Azure Token Service" },
  { id: "azure/azure-video-indexer", label: "Azure Video Indexer" },
  { id: "azure/azure-virtual-desktop", label: "Azure Virtual Desktop" },
  { id: "azure/azure-vmware-solution", label: "Azure VMware Solution" },
  { id: "azure/azure-workbooks", label: "Azure Workbooks" },
  { id: "azure/azureattestation", label: "AzureAttestation" },
  { id: "azure/azurite", label: "Azurite" },
  { id: "azure/backlog", label: "Backlog" },
  { id: "azure/backup-vault", label: "Backup Vault" },
  { id: "azure/bare-metal-infrastructure", label: "Bare Metal Infrastructure" },
  { id: "azure/bastions", label: "Bastions" },
  { id: "azure/batch-accounts", label: "Batch Accounts" },
  { id: "azure/batch-ai", label: "Batch AI" },
  { id: "azure/biz-talk", label: "Biz Talk" },
  { id: "azure/blob-block", label: "Blob Block" },
  { id: "azure/blob-page", label: "Blob Page" },
  { id: "azure/blockchain-applications", label: "Blockchain Applications" },
  { id: "azure/blueprints", label: "Blueprints" },
  { id: "azure/bonsai", label: "Bonsai" },
  { id: "azure/bot-services", label: "Bot Services" },
  { id: "azure/branch", label: "Branch" },
  { id: "azure/breeze", label: "Breeze" },
  { id: "azure/browser", label: "Browser" },
  { id: "azure/bug", label: "Bug" },
  { id: "azure/builds", label: "Builds" },
  { id: "azure/business-process-tracking", label: "Business Process Tracking" },
  { id: "azure/cache", label: "Cache" },
  { id: "azure/cache-redis", label: "Cache Redis" },
  { id: "azure/capacity-reservation-groups", label: "Capacity Reservation Groups" },
  { id: "azure/cdn-profiles", label: "CDN Profiles" },
  { id: "azure/central-service-instance-for-sap", label: "Central Service Instance For SAP" },
  { id: "azure/ceres", label: "Ceres" },
  { id: "azure/change-analysis", label: "Change Analysis" },
  { id: "azure/client-apps", label: "Client Apps" },
  { id: "azure/cloud-services-classic", label: "Cloud Services Classic" },
  { id: "azure/cloud-services-extended-support", label: "Cloud Services extended support" },
  { id: "azure/cloudtest", label: "CloudTest" },
  { id: "azure/code", label: "Code" },
  { id: "azure/code-optimization", label: "Code Optimization" },
  { id: "azure/cognitive-search", label: "Cognitive Search" },
  { id: "azure/cognitive-services", label: "Cognitive Services" },
  { id: "azure/cognitive-services-decisions", label: "Cognitive Services Decisions" },
  { id: "azure/collaborative-service", label: "Collaborative Service" },
  { id: "azure/commit", label: "Commit" },
  { id: "azure/community-images", label: "Community Images" },
  { id: "azure/compliance", label: "Compliance" },
  { id: "azure/compliance-center", label: "Compliance Center" },
  { id: "azure/compute-fleet", label: "Compute Fleet" },
  { id: "azure/computer-vision", label: "Computer Vision" },
  { id: "azure/conditional-access", label: "Conditional Access" },
  { id: "azure/confidential-ledgers", label: "Confidential Ledgers" },
  { id: "azure/connected-cache", label: "Connected Cache" },
  { id: "azure/connected-vehicle-platform", label: "Connected Vehicle Platform" },
  { id: "azure/connections", label: "Connections" },
  { id: "azure/consortium", label: "Consortium" },
  { id: "azure/container-apps-environments", label: "Container Apps Environments" },
  { id: "azure/container-instances", label: "Container Instances" },
  { id: "azure/container-registries", label: "Container Registries" },
  { id: "azure/container-services-deprecated", label: "Container Services Deprecated" },
  { id: "azure/content-moderators", label: "Content Moderators" },
  { id: "azure/content-safety", label: "Content Safety" },
  { id: "azure/controls", label: "Controls" },
  { id: "azure/controls-horizontal", label: "Controls Horizontal" },
  { id: "azure/cost-alerts", label: "Cost Alerts" },
  { id: "azure/cost-analysis", label: "Cost Analysis" },
  { id: "azure/cost-budgets", label: "Cost Budgets" },
  { id: "azure/cost-export", label: "Cost Export" },
  { id: "azure/cost-management", label: "Cost Management" },
  { id: "azure/cost-management-and-billing", label: "Cost Management and Billing" },
  { id: "azure/counter", label: "Counter" },
  { id: "azure/cubes", label: "Cubes" },
  { id: "azure/custom-ip-prefix", label: "Custom IP Prefix" },
  { id: "azure/custom-vision", label: "Custom Vision" },
  { id: "azure/customer-lockbox-for-microsoft-azure", label: "Customer Lockbox for Microsoft Azure" },
  { id: "azure/dashboard", label: "Dashboard" },
  { id: "azure/dashboard-hub", label: "Dashboard Hub" },
  { id: "azure/data-box", label: "Data Box" },
  { id: "azure/data-collection-rules", label: "Data Collection Rules" },
  { id: "azure/data-factories", label: "Data Factories" },
  { id: "azure/data-lake-analytics", label: "Data Lake Analytics" },
  { id: "azure/data-lake-storage-gen1", label: "Data Lake Storage Gen1" },
  { id: "azure/data-lake-store-gen1", label: "Data Lake Store Gen1" },
  { id: "azure/data-share-invitations", label: "Data Share Invitations" },
  { id: "azure/data-shares", label: "Data Shares" },
  { id: "azure/data-virtualization", label: "Data Virtualization" },
  { id: "azure/database-instance-for-sap", label: "Database Instance For SAP" },
  { id: "azure/ddos-custom-policy", label: "DDoS Custom Policy" },
  { id: "azure/ddos-protection-plans", label: "DDoS Protection Plans" },
  { id: "azure/dedicated-hsm", label: "Dedicated HSM" },
  { id: "azure/defender-cm-local-manager", label: "Defender CM Local Manager" },
  { id: "azure/defender-dcs-controller", label: "Defender DCS Controller" },
  { id: "azure/defender-distributer-control-system", label: "Defender Distributer Control System" },
  { id: "azure/defender-engineering-station", label: "Defender Engineering Station" },
  { id: "azure/defender-external-management", label: "Defender External Management" },
  { id: "azure/defender-freezer-monitor", label: "Defender Freezer Monitor" },
  { id: "azure/defender-historian", label: "Defender Historian" },
  { id: "azure/defender-hmi", label: "Defender HMI" },
  { id: "azure/defender-industrial-packaging-system", label: "Defender Industrial Packaging System" },
  { id: "azure/defender-industrial-printer", label: "Defender Industrial Printer" },
  { id: "azure/defender-industrial-robot", label: "Defender Industrial Robot" },
  { id: "azure/defender-industrial-scale-system", label: "Defender Industrial Scale System" },
  { id: "azure/defender-marquee", label: "Defender Marquee" },
  { id: "azure/defender-meter", label: "Defender Meter" },
  { id: "azure/defender-plc", label: "Defender PLC" },
  { id: "azure/defender-pneumatic-device", label: "Defender Pneumatic Device" },
  { id: "azure/defender-programable-board", label: "Defender Programable Board" },
  { id: "azure/defender-relay", label: "Defender Relay" },
  { id: "azure/defender-robot-controller", label: "Defender Robot Controller" },
  { id: "azure/defender-rtu", label: "Defender RTU" },
  { id: "azure/defender-sensor", label: "Defender Sensor" },
  { id: "azure/defender-slot", label: "Defender Slot" },
  { id: "azure/defender-web-guiding-system", label: "Defender Web Guiding System" },
  { id: "azure/detonation", label: "Detonation" },
  { id: "azure/dev-console", label: "Dev Console" },
  { id: "azure/device-compliance", label: "Device Compliance" },
  { id: "azure/device-configuration", label: "Device Configuration" },
  { id: "azure/device-enrollment", label: "Device Enrollment" },
  { id: "azure/device-provisioning-services", label: "Device Provisioning Services" },
  { id: "azure/device-security-apple", label: "Device Security Apple" },
  { id: "azure/device-security-google", label: "Device Security Google" },
  { id: "azure/device-security-windows", label: "Device Security Windows" },
  { id: "azure/device-update-iot-hub", label: "Device Update IoT Hub" },
  { id: "azure/devices", label: "Devices" },
  { id: "azure/devops-starter", label: "DevOps Starter" },
  { id: "azure/devtest-labs", label: "DevTest Labs" },
  { id: "azure/diagnostics-settings", label: "Diagnostics Settings" },
  { id: "azure/digital-twins", label: "Digital Twins" },
  { id: "azure/disconnected-operations", label: "Disconnected Operations" },
  { id: "azure/disk-encryption-sets", label: "Disk Encryption Sets" },
  { id: "azure/disk-pool", label: "Disk Pool" },
  { id: "azure/disks", label: "Disks" },
  { id: "azure/disks-classic", label: "Disks Classic" },
  { id: "azure/disks-snapshots", label: "Disks Snapshots" },
  { id: "azure/dns-multistack", label: "DNS Multistack" },
  { id: "azure/dns-private-resolver", label: "DNS Private Resolver" },
  { id: "azure/dns-security-policy", label: "DNS Security Policy" },
  { id: "azure/dns-zones", label: "DNS Zones" },
  { id: "azure/download", label: "Download" },
  { id: "azure/ebooks", label: "eBooks" },
  { id: "azure/edge-actions", label: "Edge Actions" },
  { id: "azure/edge-management", label: "Edge Management" },
  { id: "azure/edge-storage-accelerator", label: "Edge Storage Accelerator" },
  { id: "azure/education", label: "Education" },
  { id: "azure/elastic-job-agents", label: "Elastic Job Agents" },
  { id: "azure/elastic-san", label: "Elastic SAN" },
  { id: "azure/endpoint-analytics", label: "Endpoint Analytics" },
  { id: "azure/engage-center-connect", label: "Engage Center Connect" },
  { id: "azure/enterprise-applications", label: "Enterprise Applications" },
  { id: "azure/entra-connect", label: "Entra Connect" },
  { id: "azure/entra-connect-health", label: "Entra Connect Health" },
  { id: "azure/entra-connect-sync", label: "Entra Connect Sync" },
  { id: "azure/entra-domain-services", label: "Entra Domain Services" },
  { id: "azure/entra-global-secure-access", label: "Entra Global Secure Access" },
  { id: "azure/entra-id-protection", label: "Entra ID Protection" },
  { id: "azure/entra-identity-custom-roles", label: "Entra Identity Custom Roles" },
  { id: "azure/entra-identity-licenses", label: "Entra Identity Licenses" },
  { id: "azure/entra-identity-risky-signins", label: "Entra Identity Risky Signins" },
  { id: "azure/entra-identity-risky-users", label: "Entra Identity Risky Users" },
  { id: "azure/entra-identity-roles-and-administrators", label: "Entra Identity Roles and Administrators" },
  { id: "azure/entra-internet-access", label: "Entra Internet Access" },
  { id: "azure/entra-managed-identities", label: "Entra Managed Identities" },
  { id: "azure/entra-private-access", label: "Entra Private Access" },
  { id: "azure/entra-privleged-identity-management", label: "Entra Privleged Identity Management" },
  { id: "azure/entra-verified-id", label: "Entra Verified ID" },
  { id: "azure/error", label: "Error" },
  { id: "azure/event-grid-domains", label: "Event Grid Domains" },
  { id: "azure/event-grid-subscriptions", label: "Event Grid Subscriptions" },
  { id: "azure/event-grid-topics", label: "Event Grid Topics" },
  { id: "azure/event-hub-clusters", label: "Event Hub Clusters" },
  { id: "azure/event-hubs", label: "Event Hubs" },
  { id: "azure/exchange-access", label: "Exchange Access" },
  { id: "azure/exchange-on-premises-access", label: "Exchange On Premises Access" },
  { id: "azure/express-route-traffic-collector", label: "Express Route Traffic Collector" },
  { id: "azure/expressroute-circuits", label: "ExpressRoute Circuits" },
  { id: "azure/expressroute-direct", label: "ExpressRoute Direct" },
  { id: "azure/extendedsecurityupdates", label: "ExtendedSecurityUpdates" },
  { id: "azure/extensions", label: "Extensions" },
  { id: "azure/external-id", label: "external id" },
  { id: "azure/external-id-modified", label: "external id modified" },
  { id: "azure/external-identities", label: "External Identities" },
  { id: "azure/face-apis", label: "Face APIs" },
  { id: "azure/feature-previews", label: "Feature Previews" },
  { id: "azure/fhir-service", label: "FHIR Service" },
  { id: "azure/fiji", label: "Fiji" },
  { id: "azure/file", label: "File" },
  { id: "azure/files", label: "Files" },
  { id: "azure/firewalls", label: "Firewalls" },
  { id: "azure/folder-blank", label: "Folder Blank" },
  { id: "azure/folder-website", label: "Folder Website" },
  { id: "azure/form-recognizers", label: "Form Recognizers" },
  { id: "azure/foundry-agent-service", label: "Foundry Agent Service" },
  { id: "azure/foundry-application", label: "Foundry Application" },
  { id: "azure/foundry-control-plane", label: "Foundry Control Plane" },
  { id: "azure/foundry-labs", label: "Foundry Labs" },
  { id: "azure/foundry-local", label: "Foundry Local" },
  { id: "azure/foundry-models", label: "Foundry Models" },
  { id: "azure/foundry-project", label: "Foundry Project" },
  { id: "azure/frd-qa", label: "FRD QA" },
  { id: "azure/free-services", label: "Free Services" },
  { id: "azure/front-door-and-cdn-profiles", label: "Front Door and CDN Profiles" },
  { id: "azure/ftp", label: "FTP" },
  { id: "azure/function-apps", label: "Function Apps" },
  { id: "azure/gear", label: "Gear" },
  { id: "azure/genomics", label: "Genomics" },
  { id: "azure/genomics-accounts", label: "Genomics Accounts" },
  { id: "azure/globe-error", label: "Globe Error" },
  { id: "azure/globe-success", label: "Globe Success" },
  { id: "azure/globe-warning", label: "Globe Warning" },
  { id: "azure/groups", label: "Groups" },
  { id: "azure/guide", label: "Guide" },
  { id: "azure/hd-insight-clusters", label: "HD Insight Clusters" },
  { id: "azure/hdi-aks-cluster", label: "HDI AKS Cluster" },
  { id: "azure/heart", label: "Heart" },
  { id: "azure/help-and-support", label: "Help and Support" },
  { id: "azure/host-groups", label: "Host Groups" },
  { id: "azure/host-pools", label: "Host Pools" },
  { id: "azure/hosts", label: "Hosts" },
  { id: "azure/hybrid-connectivity-hub", label: "Hybrid Connectivity Hub" },
  { id: "azure/icm-troubleshooting", label: "IcM Troubleshooting" },
  { id: "azure/identity-governance", label: "Identity Governance" },
  { id: "azure/identity-secure-score", label: "Identity Secure Score" },
  { id: "azure/image", label: "Image" },
  { id: "azure/image-definitions", label: "Image Definitions" },
  { id: "azure/image-templates", label: "Image Templates" },
  { id: "azure/image-versions", label: "Image Versions" },
  { id: "azure/images", label: "Images" },
  { id: "azure/immersive-readers", label: "Immersive Readers" },
  { id: "azure/import-export-jobs", label: "Import Export Jobs" },
  { id: "azure/industrial-iot", label: "Industrial IoT" },
  { id: "azure/information", label: "Information" },
  { id: "azure/input-output", label: "Input Output" },
  { id: "azure/instance-pools", label: "Instance Pools" },
  { id: "azure/integration-accounts", label: "Integration Accounts" },
  { id: "azure/integration-environments", label: "Integration Environments" },
  { id: "azure/integration-service-environments", label: "Integration Service Environments" },
  { id: "azure/internet-analyzer-profiles", label: "Internet Analyzer Profiles" },
  { id: "azure/intune", label: "Intune" },
  { id: "azure/intune-app-protection", label: "Intune App Protection" },
  { id: "azure/intune-for-education", label: "Intune For Education" },
  { id: "azure/intune-trends", label: "Intune Trends" },
  { id: "azure/iot-central-applications", label: "IoT Central Applications" },
  { id: "azure/iot-edge", label: "IoT Edge" },
  { id: "azure/iot-hub", label: "IoT Hub" },
  { id: "azure/ip-address-manager", label: "IP Address manager" },
  { id: "azure/ip-groups", label: "IP Groups" },
  { id: "azure/journey-hub", label: "Journey Hub" },
  { id: "azure/key-vaults", label: "Key Vaults" },
  { id: "azure/keys", label: "Keys" },
  { id: "azure/kubernetes-fleet-manager", label: "Kubernetes Fleet Manager" },
  { id: "azure/kubernetes-hub", label: "Kubernetes Hub" },
  { id: "azure/kubernetes-services", label: "Kubernetes Services" },
  { id: "azure/lab-accounts", label: "Lab Accounts" },
  { id: "azure/lab-services", label: "Lab Services" },
  { id: "azure/landing-zone", label: "Landing Zone" },
  { id: "azure/language", label: "Language" },
  { id: "azure/language-understanding", label: "Language Understanding" },
  { id: "azure/launch-portal", label: "Launch Portal" },
  { id: "azure/learn", label: "Learn" },
  { id: "azure/load-balancer-hub", label: "Load Balancer Hub" },
  { id: "azure/load-balancers", label: "Load Balancers" },
  { id: "azure/load-test", label: "Load Test" },
  { id: "azure/load-testing", label: "Load Testing" },
  { id: "azure/local-network-gateways", label: "Local Network Gateways" },
  { id: "azure/location", label: "Location" },
  { id: "azure/log-analytics-query-pack", label: "Log Analytics Query Pack" },
  { id: "azure/log-analytics-workspaces", label: "Log Analytics Workspaces" },
  { id: "azure/log-streaming", label: "Log Streaming" },
  { id: "azure/logic-apps", label: "Logic Apps" },
  { id: "azure/logic-apps-custom-connector", label: "Logic Apps Custom Connector" },
  { id: "azure/logic-apps-template", label: "Logic Apps Template" },
  { id: "azure/machine-learning", label: "Machine Learning" },
  { id: "azure/machine-learning-studio-classic-web-services", label: "Machine Learning Studio Classic Web Services" },
  { id: "azure/machine-learning-studio-web-service-plans", label: "Machine Learning Studio Web Service Plans" },
  { id: "azure/machine-learning-studio-workspaces", label: "Machine Learning Studio Workspaces" },
  { id: "azure/machinesazurearc", label: "MachinesAzureArc" },
  { id: "azure/maintenance-configuration", label: "Maintenance Configuration" },
  { id: "azure/managed-applications-center", label: "Managed Applications Center" },
  { id: "azure/managed-database", label: "Managed Database" },
  { id: "azure/managed-desktop", label: "Managed Desktop" },
  { id: "azure/managed-devops-pools", label: "Managed DevOps Pools" },
  { id: "azure/managed-file-shares", label: "Managed File Shares" },
  { id: "azure/managed-identities", label: "Managed Identities" },
  { id: "azure/managed-instance-apache-cassandra", label: "Managed Instance Apache Cassandra" },
  { id: "azure/managed-service-fabric", label: "Managed Service Fabric" },
  { id: "azure/management-groups", label: "Management Groups" },
  { id: "azure/management-portal", label: "Management Portal" },
  { id: "azure/marketplace", label: "Marketplace" },
  { id: "azure/marketplace-management", label: "Marketplace Management" },
  { id: "azure/media", label: "Media" },
  { id: "azure/media-file", label: "Media File" },
  { id: "azure/medtech-service", label: "MedTech Service" },
  { id: "azure/mesh-applications", label: "Mesh Applications" },
  { id: "azure/metrics", label: "Metrics" },
  { id: "azure/metrics-advisor", label: "Metrics Advisor" },
  { id: "azure/microsoft-defender-easm", label: "Microsoft Defender EASM" },
  { id: "azure/microsoft-defender-for-cloud", label: "Microsoft Defender for Cloud" },
  { id: "azure/microsoft-defender-for-iot", label: "Microsoft Defender for IoT" },
  { id: "azure/microsoft-dev-box", label: "Microsoft Dev Box" },
  { id: "azure/microsoft-discovery", label: "Microsoft Discovery" },
  { id: "azure/mindaro", label: "Mindaro" },
  { id: "azure/mission-landing-zone", label: "Mission Landing Zone" },
  { id: "azure/mobile", label: "Mobile" },
  { id: "azure/mobile-engagement", label: "Mobile Engagement" },
  { id: "azure/mobile-networks", label: "Mobile Networks" },
  { id: "azure/modular-data-center", label: "Modular Data Center" },
  { id: "azure/module", label: "Module" },
  { id: "azure/monitor", label: "Monitor" },
  { id: "azure/monitor-health-models", label: "Monitor Health Models" },
  { id: "azure/multi-factor-authentication", label: "Multi Factor Authentication" },
  { id: "azure/multi-tenancy", label: "Multi Tenancy" },
  { id: "azure/multifactor-authentication", label: "Multifactor Authentication" },
  { id: "azure/my-customers", label: "My Customers" },
  { id: "azure/nat", label: "NAT" },
  { id: "azure/network-foundation-hub", label: "Network Foundation Hub" },
  { id: "azure/network-interfaces", label: "Network Interfaces" },
  { id: "azure/network-managers", label: "Network Managers" },
  { id: "azure/network-security-groups", label: "Network Security Groups" },
  { id: "azure/network-security-hub", label: "Network Security Hub" },
  { id: "azure/network-security-perimeters", label: "Network Security Perimeters" },
  { id: "azure/network-watcher", label: "Network Watcher" },
  { id: "azure/notification-hub-namespaces", label: "Notification Hub Namespaces" },
  { id: "azure/notification-hubs", label: "Notification Hubs" },
  { id: "azure/on-premises-data-gateways", label: "On Premises Data Gateways" },
  { id: "azure/open-supply-chain-platform", label: "Open Supply Chain Platform" },
  { id: "azure/operation-log-classic", label: "Operation Log Classic" },
  { id: "azure/oracle-database", label: "Oracle Database" },
  { id: "azure/os-images-classic", label: "OS Images Classic" },
  { id: "azure/osconfig", label: "OSConfig" },
  { id: "azure/outbound-connection", label: "Outbound Connection" },
  { id: "azure/partner-namespace", label: "Partner Namespace" },
  { id: "azure/partner-registration", label: "Partner Registration" },
  { id: "azure/partner-topic", label: "Partner Topic" },
  { id: "azure/peering-service", label: "Peering Service" },
  { id: "azure/peerings", label: "Peerings" },
  { id: "azure/personalizers", label: "Personalizers" },
  { id: "azure/planetary-computer-pro", label: "Planetary Computer Pro" },
  { id: "azure/policy", label: "Policy" },
  { id: "azure/power", label: "Power" },
  { id: "azure/power-bi-embedded", label: "Power BI Embedded" },
  { id: "azure/power-platform", label: "Power Platform" },
  { id: "azure/power-up", label: "Power Up" },
  { id: "azure/powershell", label: "Powershell" },
  { id: "azure/preview-features", label: "Preview Features" },
  { id: "azure/private-endpoints", label: "Private Endpoints" },
  { id: "azure/private-link", label: "Private Link" },
  { id: "azure/private-link-service", label: "Private Link Service" },
  { id: "azure/private-link-services", label: "Private Link Services" },
  { id: "azure/process-explorer", label: "Process Explorer" },
  { id: "azure/production-ready-database", label: "Production Ready Database" },
  { id: "azure/promethus", label: "promethus" },
  { id: "azure/proximity-placement-groups", label: "Proximity Placement Groups" },
  { id: "azure/public-ip-addresses", label: "Public IP Addresses" },
  { id: "azure/public-ip-addresses-classic", label: "Public IP Addresses Classic" },
  { id: "azure/public-ip-prefixes", label: "Public IP Prefixes" },
  { id: "azure/pubsub", label: "pubsub" },
  { id: "azure/qna-makers", label: "QnA Makers" },
  { id: "azure/quickstart-center", label: "Quickstart Center" },
  { id: "azure/recent", label: "Recent" },
  { id: "azure/recovery-services-vaults", label: "Recovery Services Vaults" },
  { id: "azure/region-management", label: "Region Management" },
  { id: "azure/relays", label: "Relays" },
  { id: "azure/remote-rendering", label: "Remote Rendering" },
  { id: "azure/reservations", label: "Reservations" },
  { id: "azure/reserved-capacity", label: "Reserved Capacity" },
  { id: "azure/reserved-ip-addresses-classic", label: "Reserved IP Addresses Classic" },
  { id: "azure/resiliency", label: "Resiliency" },
  { id: "azure/resource-explorer", label: "Resource Explorer" },
  { id: "azure/resource-graph-explorer", label: "Resource Graph Explorer" },
  { id: "azure/resource-group-list", label: "Resource Group List" },
  { id: "azure/resource-groups", label: "Resource Groups" },
  { id: "azure/resource-guard", label: "Resource Guard" },
  { id: "azure/resource-linked", label: "Resource Linked" },
  { id: "azure/resource-management-private-link", label: "Resource Management Private Link" },
  { id: "azure/resource-mover", label: "Resource Mover" },
  { id: "azure/resources-provider", label: "Resources Provider" },
  { id: "azure/restore-points", label: "Restore Points" },
  { id: "azure/restore-points-collections", label: "Restore Points Collections" },
  { id: "azure/route-filters", label: "Route Filters" },
  { id: "azure/route-tables", label: "Route Tables" },
  { id: "azure/rtos", label: "RTOS" },
  { id: "azure/savings-plans", label: "Savings Plans" },
  { id: "azure/scheduled-actions", label: "Scheduled Actions" },
  { id: "azure/scheduler", label: "Scheduler" },
  { id: "azure/scheduler-job-collections", label: "Scheduler Job Collections" },
  { id: "azure/scvmm-management-servers", label: "SCVMM Management Servers" },
  { id: "azure/search", label: "Search" },
  { id: "azure/search-grid", label: "Search Grid" },
  { id: "azure/security", label: "Security" },
  { id: "azure/security-baselines", label: "Security Baselines" },
  { id: "azure/sendgrid-accounts", label: "SendGrid Accounts" },
  { id: "azure/server-farm", label: "Server Farm" },
  { id: "azure/serverless-search", label: "Serverless Search" },
  { id: "azure/service-catalog-mad", label: "Service Catalog MAD" },
  { id: "azure/service-endpoint-policies", label: "Service Endpoint Policies" },
  { id: "azure/service-fabric-clusters", label: "Service Fabric Clusters" },
  { id: "azure/service-group-relationships", label: "Service Group Relationships" },
  { id: "azure/service-groups", label: "Service Groups" },
  { id: "azure/service-health", label: "Service Health" },
  { id: "azure/service-providers", label: "Service Providers" },
  { id: "azure/shared-image-galleries", label: "Shared Image Galleries" },
  { id: "azure/signalr", label: "SignalR" },
  { id: "azure/software-as-a-service", label: "Software as a Service" },
  { id: "azure/software-updates", label: "Software Updates" },
  { id: "azure/solutions", label: "Solutions" },
  { id: "azure/sonic-dash", label: "Sonic Dash" },
  { id: "azure/spatial-anchor-accounts", label: "Spatial Anchor Accounts" },
  { id: "azure/speech-services", label: "Speech Services" },
  { id: "azure/spot-vm", label: "Spot VM" },
  { id: "azure/spot-vmss", label: "Spot VMSS" },
  { id: "azure/sql-data-warehouses", label: "SQL Data Warehouses" },
  { id: "azure/sql-database", label: "SQL Database" },
  { id: "azure/sql-database-fleet-manager", label: "SQL Database Fleet Manager" },
  { id: "azure/sql-elastic-pools", label: "SQL Elastic Pools" },
  { id: "azure/sql-managed-instance", label: "SQL Managed Instance" },
  { id: "azure/sql-server", label: "SQL Server" },
  { id: "azure/sql-server-registries", label: "SQL Server Registries" },
  { id: "azure/ssd", label: "SSD" },
  { id: "azure/ssh-keys", label: "SSH Keys" },
  { id: "azure/ssis-lift-and-shift-ir", label: "SSIS Lift And Shift IR" },
  { id: "azure/stack-hci-premium", label: "Stack HCI Premium" },
  { id: "azure/stage-maps", label: "Stage Maps" },
  { id: "azure/static-apps", label: "Static Apps" },
  { id: "azure/storage-accounts", label: "Storage Accounts" },
  { id: "azure/storage-accounts-classic", label: "Storage Accounts Classic" },
  { id: "azure/storage-actions", label: "Storage Actions" },
  { id: "azure/storage-azure-files", label: "Storage Azure Files" },
  { id: "azure/storage-container", label: "Storage Container" },
  { id: "azure/storage-explorer", label: "Storage Explorer" },
  { id: "azure/storage-functions", label: "Storage Functions" },
  { id: "azure/storage-hubs", label: "Storage Hubs" },
  { id: "azure/storage-queue", label: "Storage Queue" },
  { id: "azure/storage-sync-services", label: "Storage Sync Services" },
  { id: "azure/storsimple-data-managers", label: "StorSimple Data Managers" },
  { id: "azure/storsimple-device-managers", label: "StorSimple Device Managers" },
  { id: "azure/stream-analytics-jobs", label: "Stream Analytics Jobs" },
  { id: "azure/subnet", label: "Subnet" },
  { id: "azure/subscriptions", label: "Subscriptions" },
  { id: "azure/system-topic", label: "System Topic" },
  { id: "azure/table", label: "Table" },
  { id: "azure/tag", label: "Tag" },
  { id: "azure/tags", label: "Tags" },
  { id: "azure/targets-management", label: "Targets Management" },
  { id: "azure/template-specs", label: "Template Specs" },
  { id: "azure/templates", label: "Templates" },
  { id: "azure/tenant-properties", label: "Tenant Properties" },
  { id: "azure/tenant-status", label: "Tenant Status" },
  { id: "azure/test-base", label: "Test Base" },
  { id: "azure/tfs-vc-repository", label: "TFS VC Repository" },
  { id: "azure/time-series-data-sets", label: "Time Series Data Sets" },
  { id: "azure/time-series-insights-access-policies", label: "Time Series Insights Access Policies" },
  { id: "azure/time-series-insights-environments", label: "Time Series Insights Environments" },
  { id: "azure/time-series-insights-event-sources", label: "Time Series Insights Event Sources" },
  { id: "azure/toolbox", label: "Toolbox" },
  { id: "azure/toolchain-orchestrator", label: "Toolchain Orchestrator" },
  { id: "azure/traffic-manager-profiles", label: "Traffic Manager Profiles" },
  { id: "azure/translator-text", label: "Translator Text" },
  { id: "azure/troubleshoot", label: "Troubleshoot" },
  { id: "azure/universal-print", label: "Universal Print" },
  { id: "azure/update-management-center", label: "Update Management Center" },
  { id: "azure/user-privacy", label: "User Privacy" },
  { id: "azure/user-settings", label: "User Settings" },
  { id: "azure/user-subscriptions", label: "User Subscriptions" },
  { id: "azure/users", label: "Users" },
  { id: "azure/verifiable-credentials", label: "Verifiable Credentials" },
  { id: "azure/verification-as-a-service", label: "Verification As A Service" },
  { id: "azure/versions", label: "Versions" },
  { id: "azure/video-analyzers", label: "Video Analyzers" },
  { id: "azure/virtual-clusters", label: "Virtual Clusters" },
  { id: "azure/virtual-instance-for-sap", label: "Virtual Instance for SAP" },
  { id: "azure/virtual-machine", label: "Virtual Machine" },
  { id: "azure/virtual-machines-classic", label: "Virtual Machines Classic" },
  { id: "azure/virtual-network-gateways", label: "Virtual Network Gateways" },
  { id: "azure/virtual-networks", label: "Virtual Networks" },
  { id: "azure/virtual-networks-classic", label: "Virtual Networks Classic" },
  { id: "azure/virtual-router", label: "Virtual Router" },
  { id: "azure/virtual-visits-builder", label: "Virtual Visits Builder" },
  { id: "azure/virtual-wan-hub", label: "Virtual WAN Hub" },
  { id: "azure/virtual-wans", label: "Virtual WANs" },
  { id: "azure/vm-app-definitions", label: "VM App Definitions" },
  { id: "azure/vm-app-versions", label: "VM App Versions" },
  { id: "azure/vm-image-version", label: "VM Image Version" },
  { id: "azure/vm-images-classic", label: "VM Images Classic" },
  { id: "azure/vm-scale-sets", label: "VM Scale Sets" },
  { id: "azure/vnet-appliance", label: "VNet Appliance" },
  { id: "azure/vpnclientwindows", label: "VPNClientWindows" },
  { id: "azure/wac", label: "WAC" },
  { id: "azure/wac-installer", label: "WAC Installer" },
  { id: "azure/web-app-database", label: "Web App + Database" },
  { id: "azure/web-application-firewall-policieswaf", label: "Web Application Firewall PoliciesWAF" },
  { id: "azure/web-jobs", label: "Web Jobs" },
  { id: "azure/web-slots", label: "Web Slots" },
  { id: "azure/web-test", label: "Web Test" },
  { id: "azure/website-power", label: "Website Power" },
  { id: "azure/website-staging", label: "Website Staging" },
  { id: "azure/windows-notification-services", label: "Windows Notification Services" },
  { id: "azure/windows10-core-services", label: "Windows10 Core Services" },
  { id: "azure/workbooks", label: "Workbooks" },
  { id: "azure/worker-container-app", label: "Worker Container App" },
  { id: "azure/workflow", label: "Workflow" },
  { id: "azure/workload-orchestration", label: "Workload Orchestration" },
  { id: "azure/workspace-gateway", label: "Workspace Gateway" },
  { id: "azure/workspaces", label: "Workspaces" },
];
