// Generato da scripts/import-microsoft365-icons.mjs a partire dalle icone Microsoft 365/Teams/Power
// Platform/Dynamics 365 (tmp/azure-icons-src/, non versionata). Non modificare a mano: rilanciare lo
// script se Microsoft aggiorna il set. 347 icone.
import type { IconOption } from "./iconifyIcons";

export const MICROSOFT365_ICON_CATALOG: IconOption[] = [
  { id: "ms365/agent365", label: "Agent365" },
  { id: "ms365/power-platform/aibuilder", label: "AIBuilder" },
  { id: "ms365/ui-blue/apps", label: "Apps" },
  { id: "ms365/ui-teams-purple/apps", label: "Apps" },
  { id: "ms365/ui-blue/apps-list-detail", label: "Apps List Detail" },
  { id: "ms365/ui-teams-purple/apps-list-detail", label: "Apps List Detail" },
  { id: "ms365/ui-blue/arrow-circle-left", label: "Arrow Circle Left" },
  { id: "ms365/ui-teams-purple/arrow-circle-left", label: "Arrow Circle Left" },
  { id: "ms365/ui-blue/arrow-circle-right", label: "Arrow Circle Right" },
  { id: "ms365/ui-teams-purple/arrow-circle-right", label: "Arrow Circle Right" },
  { id: "ms365/ui-blue/arrow-clockwise", label: "Arrow Clockwise" },
  { id: "ms365/ui-teams-purple/arrow-clockwise", label: "Arrow Clockwise" },
  { id: "ms365/ui-blue/arrow-down", label: "Arrow Down" },
  { id: "ms365/ui-teams-purple/arrow-down", label: "Arrow Down" },
  { id: "ms365/ui-blue/arrow-download", label: "Arrow Download" },
  { id: "ms365/ui-teams-purple/arrow-download", label: "Arrow Download" },
  { id: "ms365/ui-blue/arrow-sync", label: "Arrow Sync" },
  { id: "ms365/ui-teams-purple/arrow-sync", label: "Arrow Sync" },
  { id: "ms365/ui-blue/arrow-upload", label: "Arrow Upload" },
  { id: "ms365/ui-teams-purple/arrow-upload", label: "Arrow Upload" },
  { id: "ms365/ui-blue/attach", label: "Attach" },
  { id: "ms365/ui-teams-purple/attach", label: "Attach" },
  { id: "ms365/ui-blue/book-contacts", label: "Book Contacts" },
  { id: "ms365/ui-teams-purple/book-contacts", label: "Book Contacts" },
  { id: "ms365/ui-blue/bot", label: "Bot" },
  { id: "ms365/ui-teams-purple/bot", label: "Bot" },
  { id: "ms365/ui-blue/building", label: "Building" },
  { id: "ms365/ui-purple/building", label: "Building" },
  { id: "ms365/ui-teams-purple/building", label: "Building" },
  { id: "ms365/ui-blue/building-cloud", label: "Building Cloud" },
  { id: "ms365/ui-blue/building-multiple", label: "Building Multiple" },
  { id: "ms365/ui-teams-purple/building-multiple", label: "Building Multiple" },
  { id: "ms365/ui-teams-purple/building-people", label: "Building People" },
  { id: "ms365/ui-blue/building-people-blue", label: "Building People Blue" },
  { id: "ms365/ui-teams-purple/building-people-teams", label: "Building People Teams" },
  { id: "ms365/ui-blue/building-retail", label: "Building Retail" },
  { id: "ms365/ui-teams-purple/building-retail", label: "Building Retail" },
  { id: "ms365/dynamics-365/businesscentral", label: "Business Central" },
  { id: "ms365/ui-blue/calculator", label: "Calculator" },
  { id: "ms365/ui-teams-purple/calculator", label: "Calculator" },
  { id: "ms365/ui-blue/calendar-month", label: "Calendar Month" },
  { id: "ms365/ui-teams-purple/calendar-month", label: "Calendar Month" },
  { id: "ms365/ui-planner-green/calendar-month", label: "Calendar Month" },
  { id: "ms365/ui-blue/call", label: "Call" },
  { id: "ms365/ui-teams-purple/call", label: "Call" },
  { id: "ms365/ui-blue/camera", label: "Camera" },
  { id: "ms365/ui-teams-purple/camera", label: "Camera" },
  { id: "ms365/ui-blue/cart", label: "Cart" },
  { id: "ms365/ui-teams-purple/cart", label: "Cart" },
  { id: "ms365/ui-blue/certificate", label: "Certificate" },
  { id: "ms365/ui-teams-purple/certificate", label: "Certificate" },
  { id: "ms365/ui-blue/chart-multiple", label: "Chart Multiple" },
  { id: "ms365/ui-teams-purple/chart-multiple", label: "Chart Multiple" },
  { id: "ms365/ui-blue/chat", label: "Chat" },
  { id: "ms365/ui-teams-purple/chat", label: "Chat" },
  { id: "ms365/ui-blue/chat-multiple", label: "Chat Multiple" },
  { id: "ms365/ui-teams-purple/chat-multiple", label: "Chat Multiple" },
  { id: "ms365/ui-blue/check", label: "Check" },
  { id: "ms365/ui-teams-purple/check", label: "Check" },
  { id: "ms365/ui-planner-green/checkmark", label: "Checkmark" },
  { id: "ms365/ui-blue/checkmark-circle", label: "Checkmark Circle" },
  { id: "ms365/ui-teams-purple/checkmark-circle", label: "Checkmark Circle" },
  { id: "ms365/ui-planner-green/checkmark-circle", label: "Checkmark Circle" },
  { id: "ms365/ui-blue/chevron-circle", label: "Chevron Circle" },
  { id: "ms365/ui-teams-purple/chevron-circle", label: "Chevron Circle" },
  { id: "ms365/ui-planner-green/clipboard", label: "Clipboard" },
  { id: "ms365/ui-blue/clipboard-task-list", label: "Clipboard Task List" },
  { id: "ms365/ui-teams-purple/clipboard-task-list", label: "Clipboard Task List" },
  { id: "ms365/ui-planner-green/clipboard-task-list", label: "Clipboard Task List" },
  { id: "ms365/ui-blue/clock", label: "Clock" },
  { id: "ms365/ui-teams-purple/clock", label: "Clock" },
  { id: "ms365/ui-planner-green/clock", label: "Clock" },
  { id: "ms365/ui-blue/clock-alarm", label: "Clock Alarm" },
  { id: "ms365/ui-teams-purple/clock-alarm", label: "Clock Alarm" },
  { id: "ms365/ui-blue/cloud", label: "Cloud" },
  { id: "ms365/ui-teams-purple/cloud", label: "Cloud" },
  { id: "ms365/ui-blue/cloud-add", label: "Cloud Add" },
  { id: "ms365/ui-teams-purple/cloud-add", label: "Cloud Add" },
  { id: "ms365/ui-blue/cloud-arrow-down", label: "Cloud Arrow Down" },
  { id: "ms365/ui-teams-purple/cloud-arrow-down", label: "Cloud Arrow Down" },
  { id: "ms365/ui-blue/cloud-arrow-up", label: "Cloud Arrow Up" },
  { id: "ms365/ui-teams-purple/cloud-arrow-up", label: "Cloud Arrow Up" },
  { id: "ms365/ui-blue/cloud-beaker", label: "Cloud Beaker" },
  { id: "ms365/ui-blue/cloud-cube", label: "Cloud Cube" },
  { id: "ms365/ui-blue/cloud-database", label: "Cloud Database" },
  { id: "ms365/ui-teams-purple/cloud-database", label: "Cloud Database" },
  { id: "ms365/ui-blue/cloud-desktop", label: "Cloud Desktop" },
  { id: "ms365/ui-teams-purple/cloud-desktop", label: "Cloud Desktop" },
  { id: "ms365/ui-blue/code", label: "Code" },
  { id: "ms365/ui-teams-purple/code", label: "Code" },
  { id: "ms365/ui-blue/column-arrow-right", label: "Column Arrow Right" },
  { id: "ms365/ui-teams-purple/column-arrow-right", label: "Column Arrow Right" },
  { id: "ms365/ui-blue/comment", label: "Comment" },
  { id: "ms365/ui-teams-purple/comment", label: "Comment" },
  { id: "ms365/ui-blue/comment-multiple", label: "Comment Multiple" },
  { id: "ms365/ui-teams-purple/comment-multiple", label: "Comment Multiple" },
  { id: "ms365/dynamics-365/commerce", label: "Commerce" },
  { id: "ms365/dynamics-365/contactcenter", label: "Contact Center" },
  { id: "ms365/copilotstudio", label: "Copilot Studio" },
  { id: "ms365/dynamics-365/customerinsights", label: "Customer Insights" },
  { id: "ms365/dynamics-365/customerservices", label: "Customer Services" },
  { id: "ms365/dynamics-365/customervoice", label: "Customer Voice" },
  { id: "ms365/ui-blue/data-area", label: "Data Area" },
  { id: "ms365/ui-teams-purple/data-area", label: "Data Area" },
  { id: "ms365/ui-blue/data-bar-vertical", label: "Data Bar Vertical" },
  { id: "ms365/ui-teams-purple/data-bar-vertical", label: "Data Bar Vertical" },
  { id: "ms365/ui-blue/data-pie", label: "Data Pie" },
  { id: "ms365/ui-teams-purple/data-pie", label: "Data Pie" },
  { id: "ms365/ui-blue/data-trending", label: "Data Trending" },
  { id: "ms365/ui-teams-purple/data-trending", label: "Data Trending" },
  { id: "ms365/ui-blue/data-trending-1", label: "Data Trending (1)" },
  { id: "ms365/ui-teams-purple/data-trending-2", label: "Data Trending (2)" },
  { id: "ms365/ui-blue/data-usage", label: "Data Usage" },
  { id: "ms365/ui-teams-purple/data-usage", label: "Data Usage" },
  { id: "ms365/ui-blue/database", label: "Database" },
  { id: "ms365/ui-teams-purple/database", label: "Database" },
  { id: "ms365/power-platform/dataverse", label: "Dataverse" },
  { id: "ms365/ui-blue/deploy", label: "Deploy" },
  { id: "ms365/ui-planner-green/deploy", label: "Deploy" },
  { id: "ms365/ui-blue/desktop-arrow-down", label: "Desktop Arrow Down" },
  { id: "ms365/ui-teams-purple/desktop-arrow-down", label: "Desktop Arrow Down" },
  { id: "ms365/ui-blue/desktop-tower", label: "Desktop Tower" },
  { id: "ms365/ui-teams-purple/desktop-tower", label: "Desktop Tower" },
  { id: "ms365/ui-blue/dismiss-circle", label: "Dismiss Circle" },
  { id: "ms365/ui-teams-purple/dismiss-circle", label: "Dismiss Circle" },
  { id: "ms365/ui-blue/document", label: "Document" },
  { id: "ms365/ui-teams-purple/document", label: "Document" },
  { id: "ms365/ui-project-green/document", label: "Document" },
  { id: "ms365/ui-blue/document-bullet-list", label: "Document Bullet List" },
  { id: "ms365/ui-teams-purple/document-bullet-list", label: "Document Bullet List" },
  { id: "ms365/ui-blue/document-bullet-list-multiple", label: "Document Bullet List Multiple" },
  { id: "ms365/ui-teams-purple/document-bullet-list-multiple", label: "Document Bullet List Multiple" },
  { id: "ms365/ui-blue/document-key", label: "Document Key" },
  { id: "ms365/ui-teams-purple/document-key", label: "Document Key" },
  { id: "ms365/ui-blue/document-lock", label: "Document Lock" },
  { id: "ms365/ui-teams-purple/document-lock", label: "Document Lock" },
  { id: "ms365/ui-blue/document-multiple", label: "Document Multiple" },
  { id: "ms365/ui-teams-purple/document-multiple", label: "Document Multiple" },
  { id: "ms365/ui-blue/document-one-page", label: "Document One Page" },
  { id: "ms365/ui-teams-purple/document-one-page", label: "Document One Page" },
  { id: "ms365/ui-blue/document-text", label: "Document Text" },
  { id: "ms365/ui-teams-purple/document-text", label: "Document Text" },
  { id: "ms365/dynamics-365/dynamics365", label: "Dynamics365" },
  { id: "ms365/ui-blue/edit", label: "Edit" },
  { id: "ms365/ui-teams-purple/edit", label: "Edit" },
  { id: "ms365/dynamics-365/fieldservice", label: "Field Service" },
  { id: "ms365/ui-blue/filmstrip-play", label: "Filmstrip Play" },
  { id: "ms365/ui-teams-purple/filmstrip-play", label: "Filmstrip Play" },
  { id: "ms365/dynamics-365/finance", label: "Finance" },
  { id: "ms365/dynamics-365/financeoperations", label: "Finance Operations" },
  { id: "ms365/ui-blue/fingerprint", label: "Fingerprint" },
  { id: "ms365/ui-teams-purple/fingerprint", label: "Fingerprint" },
  { id: "ms365/ui-blue/flag", label: "Flag" },
  { id: "ms365/ui-teams-purple/flag", label: "Flag" },
  { id: "ms365/ui-blue/folder-multiple", label: "Folder Multiple" },
  { id: "ms365/ui-teams-purple/folder-multiple", label: "Folder Multiple" },
  { id: "ms365/ui-blue/folder-open", label: "Folder Open" },
  { id: "ms365/ui-teams-purple/folder-open", label: "Folder Open" },
  { id: "ms365/ui-blue/folder-open-vertical", label: "Folder Open Vertical" },
  { id: "ms365/ui-teams-purple/folder-open-vertical", label: "Folder Open Vertical" },
  { id: "ms365/ui-blue/folder-people", label: "Folder People" },
  { id: "ms365/ui-teams-purple/folder-people", label: "Folder People" },
  { id: "ms365/ui-blue/globe", label: "Globe" },
  { id: "ms365/ui-teams-purple/globe", label: "Globe" },
  { id: "ms365/ui-blue/grid-circles", label: "Grid Circles" },
  { id: "ms365/ui-blue/handshake", label: "Handshake" },
  { id: "ms365/ui-blue/hat-graduation", label: "Hat Graduation" },
  { id: "ms365/ui-teams-purple/hat-graduation", label: "Hat Graduation" },
  { id: "ms365/ui-blue/headset", label: "Headset" },
  { id: "ms365/ui-teams-purple/headset", label: "Headset" },
  { id: "ms365/ui-blue/heart", label: "Heart" },
  { id: "ms365/ui-teams-purple/heart", label: "Heart" },
  { id: "ms365/ui-blue/heart-pulse", label: "Heart Pulse" },
  { id: "ms365/ui-teams-purple/heart-pulse", label: "Heart Pulse" },
  { id: "ms365/dynamics-365/humanresources", label: "Human Resources" },
  { id: "ms365/ui-blue/image", label: "Image" },
  { id: "ms365/ui-teams-purple/image", label: "Image" },
  { id: "ms365/dynamics-365/intelligentordermanagement", label: "Intelligent Order Management" },
  { id: "ms365/ui-blue/key", label: "Key" },
  { id: "ms365/ui-teams-purple/key", label: "Key" },
  { id: "ms365/ui-blue/laptop", label: "Laptop" },
  { id: "ms365/ui-teams-purple/laptop", label: "Laptop" },
  { id: "ms365/ui-blue/layer-diagonal", label: "Layer Diagonal" },
  { id: "ms365/ui-teams-purple/layer-diagonal", label: "Layer Diagonal" },
  { id: "ms365/ui-blue/lightbulb", label: "Lightbulb" },
  { id: "ms365/ui-teams-purple/lightbulb", label: "Lightbulb" },
  { id: "ms365/ui-planner-green/lightbulb", label: "Lightbulb" },
  { id: "ms365/ui-blue/lightbulb-checkmark", label: "Lightbulb Checkmark" },
  { id: "ms365/ui-teams-purple/lightbulb-checkmark", label: "Lightbulb Checkmark" },
  { id: "ms365/ui-blue/lock-closed", label: "Lock Closed" },
  { id: "ms365/ui-teams-purple/lock-closed", label: "Lock Closed" },
  { id: "ms365/ui-blue/lock-shield", label: "Lock Shield" },
  { id: "ms365/ui-teams-purple/lock-shield", label: "Lock Shield" },
  { id: "ms365/ui-blue/mail", label: "Mail" },
  { id: "ms365/ui-teams-purple/mail", label: "Mail" },
  { id: "ms365/ui-blue/mail-alert", label: "Mail Alert" },
  { id: "ms365/ui-teams-purple/mail-alert", label: "Mail Alert" },
  { id: "ms365/ui-blue/mail-attach", label: "Mail Attach" },
  { id: "ms365/ui-teams-purple/mail-attach", label: "Mail Attach" },
  { id: "ms365/ui-blue/mail-error", label: "Mail Error" },
  { id: "ms365/ui-teams-purple/mail-error", label: "Mail Error" },
  { id: "ms365/ui-blue/mail-read", label: "Mail Read" },
  { id: "ms365/ui-teams-purple/mail-read", label: "Mail Read" },
  { id: "ms365/ui-blue/map", label: "Map" },
  { id: "ms365/ui-teams-purple/map", label: "Map" },
  { id: "ms365/ui-blue/megaphone-loud", label: "Megaphone Loud" },
  { id: "ms365/ui-teams-purple/megaphone-loud", label: "Megaphone Loud" },
  { id: "ms365/ui-project-green/megaphone-loud", label: "Megaphone Loud" },
  { id: "ms365/ui-blue/merge", label: "Merge" },
  { id: "ms365/ui-teams-purple/merge", label: "Merge" },
  { id: "ms365/ui-blue/notebook", label: "Notebook" },
  { id: "ms365/ui-teams-purple/notebook", label: "Notebook" },
  { id: "ms365/ui-blue/number-circle-1", label: "Number Circle 1" },
  { id: "ms365/ui-teams-purple/number-circle-1", label: "Number Circle 1" },
  { id: "ms365/ui-blue/number-circle-2", label: "Number Circle 2" },
  { id: "ms365/ui-teams-purple/number-circle-2", label: "Number Circle 2" },
  { id: "ms365/ui-blue/number-circle-3", label: "Number Circle 3" },
  { id: "ms365/ui-teams-purple/number-circle-3", label: "Number Circle 3" },
  { id: "ms365/ui-blue/number-circle-4", label: "Number Circle 4" },
  { id: "ms365/ui-teams-purple/number-circle-4", label: "Number Circle 4" },
  { id: "ms365/ui-blue/organization", label: "Organization" },
  { id: "ms365/ui-teams-purple/organization", label: "Organization" },
  { id: "ms365/ui-planner-green/organization", label: "Organization" },
  { id: "ms365/ui-sharepoint-teal/organization", label: "Organization" },
  { id: "ms365/ui-blue/organization-horizontal", label: "Organization Horizontal" },
  { id: "ms365/ui-teams-purple/organization-horizontal", label: "Organization Horizontal" },
  { id: "ms365/ui-blue/panel-left-header", label: "Panel Left Header" },
  { id: "ms365/ui-blue/panel-left-header-key", label: "Panel Left Header Key" },
  { id: "ms365/ui-teams-purple/panel-left-header-key", label: "Panel Left Header Key" },
  { id: "ms365/ui-blue/payment", label: "Payment" },
  { id: "ms365/ui-teams-purple/payment", label: "Payment" },
  { id: "ms365/ui-blue/people", label: "People" },
  { id: "ms365/ui-teams-purple/people", label: "People" },
  { id: "ms365/ui-blue/people-audience", label: "People Audience" },
  { id: "ms365/ui-teams-purple/people-audience", label: "People Audience" },
  { id: "ms365/ui-blue/people-community", label: "People Community" },
  { id: "ms365/ui-blue/people-settings", label: "People Settings" },
  { id: "ms365/ui-teams-purple/people-settings", label: "People Settings" },
  { id: "ms365/ui-blue/people-team", label: "People Team" },
  { id: "ms365/ui-teams-purple/people-team", label: "People Team" },
  { id: "ms365/ui-blue/person", label: "Person" },
  { id: "ms365/ui-teams-purple/person", label: "Person" },
  { id: "ms365/ui-blue/person-accounts", label: "Person Accounts" },
  { id: "ms365/ui-teams-purple/person-accounts", label: "Person Accounts" },
  { id: "ms365/ui-blue/person-desktop", label: "Person Desktop" },
  { id: "ms365/ui-teams-purple/person-desktop", label: "Person Desktop" },
  { id: "ms365/ui-blue/person-settings", label: "Person Settings" },
  { id: "ms365/ui-teams-purple/person-settings", label: "Person Settings" },
  { id: "ms365/ui-blue/person-square", label: "Person Square" },
  { id: "ms365/ui-teams-purple/person-square", label: "Person Square" },
  { id: "ms365/ui-blue/person-wrench", label: "Person Wrench" },
  { id: "ms365/ui-teams-purple/person-wrench", label: "Person Wrench" },
  { id: "ms365/ui-blue/phone", label: "Phone" },
  { id: "ms365/ui-teams-purple/phone", label: "Phone" },
  { id: "ms365/ui-blue/phone-desktop", label: "Phone Desktop" },
  { id: "ms365/ui-teams-purple/phone-desktop", label: "Phone Desktop" },
  { id: "ms365/ui-blue/phone-laptop", label: "Phone Laptop" },
  { id: "ms365/ui-teams-purple/phone-laptop", label: "Phone Laptop" },
  { id: "ms365/ui-blue/phone-tablet", label: "Phone Tablet" },
  { id: "ms365/ui-teams-purple/phone-tablet", label: "Phone Tablet" },
  { id: "ms365/ui-blue/phone-update", label: "Phone Update" },
  { id: "ms365/ui-teams-purple/phone-update", label: "Phone Update" },
  { id: "ms365/power-platform/powerapps", label: "Power Apps" },
  { id: "ms365/power-platform/powerautomate", label: "Power Automate" },
  { id: "ms365/power-platform/powerpages", label: "Power Pages" },
  { id: "ms365/power-platform/powerplatform", label: "Power Platform" },
  { id: "ms365/ui-blue/presenter", label: "Presenter" },
  { id: "ms365/ui-teams-purple/presenter", label: "Presenter" },
  { id: "ms365/dynamics-365/projectoperations", label: "Project Operations" },
  { id: "ms365/ui-blue/question-circle", label: "Question Circle" },
  { id: "ms365/ui-teams-purple/question-circle", label: "Question Circle" },
  { id: "ms365/ui-blue/radar", label: "Radar" },
  { id: "ms365/ui-teams-purple/radar", label: "Radar" },
  { id: "ms365/ui-blue/receipt", label: "Receipt" },
  { id: "ms365/ui-teams-purple/receipt", label: "Receipt" },
  { id: "ms365/ui-blue/ribbon", label: "Ribbon" },
  { id: "ms365/ui-teams-purple/ribbon", label: "Ribbon" },
  { id: "ms365/ui-planner-green/ribbon-planner", label: "Ribbon Planner" },
  { id: "ms365/ui-blue/ribbon-star", label: "Ribbon Star" },
  { id: "ms365/ui-teams-purple/ribbon-star", label: "Ribbon Star" },
  { id: "ms365/ui-blue/road-cone", label: "Road Cone" },
  { id: "ms365/ui-teams-purple/road-cone", label: "Road Cone" },
  { id: "ms365/dynamics-365/sales", label: "Sales" },
  { id: "ms365/dynamics-365/salesinsights", label: "Sales Insights" },
  { id: "ms365/ui-blue/script", label: "Script" },
  { id: "ms365/ui-teams-purple/script", label: "Script" },
  { id: "ms365/ui-blue/search", label: "Search" },
  { id: "ms365/ui-teams-purple/search", label: "Search" },
  { id: "ms365/ui-blue/select-all", label: "Select All" },
  { id: "ms365/ui-teams-purple/select-all", label: "Select All" },
  { id: "ms365/ui-blue/settings", label: "Settings" },
  { id: "ms365/ui-purple/settings", label: "Settings" },
  { id: "ms365/ui-teams-purple/settings", label: "Settings" },
  { id: "ms365/ui-blue/settings-cog-multiple", label: "Settings Cog Multiple" },
  { id: "ms365/ui-teams-purple/settings-cog-multiple", label: "Settings Cog Multiple" },
  { id: "ms365/ui-blue/shapes-three", label: "Shapes Three" },
  { id: "ms365/ui-blue/share", label: "Share" },
  { id: "ms365/ui-teams-purple/share", label: "Share" },
  { id: "ms365/ui-blue/share-screen-person", label: "Share Screen Person" },
  { id: "ms365/ui-teams-purple/share-screen-person", label: "Share Screen Person" },
  { id: "ms365/ui-blue/share-screen-person-overlay", label: "Share Screen Person Overlay" },
  { id: "ms365/ui-teams-purple/share-screen-person-overlay", label: "Share Screen Person Overlay" },
  { id: "ms365/ui-blue/shield-error", label: "Shield Error" },
  { id: "ms365/ui-teams-purple/shield-error", label: "Shield Error" },
  { id: "ms365/ui-blue/shifts-activity", label: "Shifts Activity" },
  { id: "ms365/ui-teams-purple/shifts-activity", label: "Shifts Activity" },
  { id: "ms365/ui-blue/shopping-bag", label: "Shopping Bag" },
  { id: "ms365/ui-teams-purple/shopping-bag", label: "Shopping Bag" },
  { id: "ms365/ui-blue/signature", label: "Signature" },
  { id: "ms365/ui-teams-purple/signature", label: "Signature" },
  { id: "ms365/ui-blue/slide-layout", label: "Slide Layout" },
  { id: "ms365/ui-teams-purple/slide-layout", label: "Slide Layout" },
  { id: "ms365/dynamics-365/supplychainmanagement", label: "Supply Chain Management" },
  { id: "ms365/ui-blue/tablet", label: "Tablet" },
  { id: "ms365/ui-teams-purple/tablet", label: "Tablet" },
  { id: "ms365/ui-blue/tablet-laptop", label: "Tablet Laptop" },
  { id: "ms365/ui-teams-purple/tablet-laptop", label: "Tablet Laptop" },
  { id: "ms365/ui-blue/tap", label: "Tap" },
  { id: "ms365/ui-purple/tap", label: "Tap" },
  { id: "ms365/ui-teams-purple/tap", label: "Tap" },
  { id: "ms365/ui-planner-green/tap", label: "Tap" },
  { id: "ms365/ui-planner-green/task-list-ltr", label: "Task List LTR" },
  { id: "ms365/ui-blue/task-list-square", label: "Task List Square" },
  { id: "ms365/ui-teams-purple/task-list-square", label: "Task List Square" },
  { id: "ms365/ui-planner-green/task-list-square", label: "Task List Square" },
  { id: "ms365/ui-project-green/text-bullet-list", label: "Text Bullet List" },
  { id: "ms365/ui-project-green/text-bullet-list-square", label: "Text Bullet List Square" },
  { id: "ms365/ui-blue/text-first-line", label: "Text First Line" },
  { id: "ms365/ui-teams-purple/text-first-line", label: "Text First Line" },
  { id: "ms365/ui-blue/text-number-list", label: "Text Number List" },
  { id: "ms365/ui-teams-purple/text-number-list", label: "Text Number List" },
  { id: "ms365/ui-blue/toolbox", label: "Toolbox" },
  { id: "ms365/ui-teams-purple/toolbox", label: "Toolbox" },
  { id: "ms365/ui-blue/top-speed", label: "Top Speed" },
  { id: "ms365/ui-teams-purple/top-speed", label: "Top Speed" },
  { id: "ms365/ui-blue/video", label: "Video" },
  { id: "ms365/ui-teams-purple/video", label: "Video" },
  { id: "ms365/ui-blue/wallet-credit-card", label: "Wallet Credit Card" },
  { id: "ms365/ui-teams-purple/wallet-credit-card", label: "Wallet Credit Card" },
  { id: "ms365/ui-blue/window", label: "Window" },
  { id: "ms365/ui-teams-purple/window", label: "Window" },
  { id: "ms365/ui-blue/window-dev-edit", label: "Window Dev Edit" },
  { id: "ms365/ui-blue/window-edit", label: "Window Edit" },
  { id: "ms365/ui-teams-purple/window-edit", label: "Window Edit" },
  { id: "ms365/ui-planner-green/window-edit", label: "Window Edit" },
  { id: "ms365/ui-blue/wrench", label: "Wrench" },
  { id: "ms365/ui-teams-purple/wrench", label: "Wrench" },
];
